admin/config/routes.rb
Rails.application.routes.draw do
  resources :pacientes
  resources :usuarios

  root 'home#index'
  get 'login' => 'login#login'
  get 'logout' => 'login#logout'
  post 'logar' => 'login#logar'

  get 'medicos' => 'medicos#index'
  get 'medico/cadastrar' => 'medicos#new', as: :new_medico
  get 'medico/:id' =>'medicos#show', as: :medico
  get 'medico/:id/editar' => 'medicos#edit', as: :edit_medico
  patch 'medico/:id' => 'medicos#update'
  delete 'medico/:id' => 'medicos#destroy'
  post 'medicos' => 'medicos#create'

  get 'sobre' => 'about#index'

  get 'tipos' => 'tipos#index'
  get 'tipos/:id/editar' => 'tipos#edit', as: :editar_tipo
  post 'tipos/:id/update' => 'tipos#update', as: :tipo_update
  get 'tipos/:id' => 'tipos#show', as: :tipo
  delete 'tipos/:id/delete' => 'tipos#delete', as: :tipo_delete
  get 'tipo/novo' => 'tipos#new', as: :tipo_new
  post 'tipo/criar' => 'tipos#criar', as: :tipo_criar

  get 'visitas' => 'visitas#index', as: :visita_index
  get 'visitas/novo' => 'visitas#new', as: :visita_new
  post 'visitas/criar' => 'visitas#criar', as: :visita_criar
  get 'visitas/:id' => 'visitas#show', as: :visita
  get 'visitas/:id/editar' => 'visitas#edit', as: :edit_visita
  post 'visitas/:id' => 'visitas#update', as: :visita_update
  delete 'visitas/:id/delete' => 'visitas#delete', as: :visita_delete

  get 'assistentes' => 'assistentes#index', as: :assistente_index
  get 'assistentes/novo' => 'assistentes#new', as: :assistente_new
  post 'assistentes/criar' => 'assistentes#criar', as: :assistente_criar
  get 'assistentes/:id' => 'assistentes#show', as: :assistente
  get 'assistentes/:id/edit' => 'assistentes#edit', as: :edit_assistente
  post 'assistentes/:id' => 'assistentes#update', as: :assistente_update
  delete 'assistentes/:id/delete' => 'assistentes#delete', as: :assistente_delete

end

admin/app/models/medico.rb
class Medico < ActiveRecord::Base
end

admin/app/controllers/medicos_controller.rb
class MedicosController < ApplicationController
  before_action :set_medico, only: [:show, :edit, :update, :destroy]

  # GET /medicos
  # GET /medicos.json
  def index
    @medicos = Medico.all
  end

  # GET /medicos/1
  # GET /medicos/1.json
  def show
  end

  # GET /medicos/new
  def new
    @medico = Medico.new
  end

  # GET /medicos/1/edit
  def edit
  end

  # POST /medicos
  # POST /medicos.json
  def create
    @medico = Medico.new(medico_params)

    respond_to do |format|
      if @medico.save
        format.html { redirect_to @medico, notice: 'Medico was successfully created.' }
        format.json { render :show, status: :created, location: @medico }
      else
        format.html { render :new }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicos/1
  # PATCH/PUT /medicos/1.json
  def update
    respond_to do |format|
      if @medico.update(medico_params)
        format.html { redirect_to @medico, notice: 'Medico was successfully updated.' }
        format.json { render :show, status: :ok, location: @medico }
      else
        format.html { render :edit }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicos/1
  # DELETE /medicos/1.json
  def destroy
    @medico.destroy
    respond_to do |format|
      format.html { redirect_to medicos_url, notice: 'Medico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medico
      @medico = Medico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medico_params
      params.require(:medico).permit(:nome, :crm, :telefone)
    end
end

admin/app/helpers/medicos_helper.rb
module MedicosHelper
end

admin/app/views/medicos/_form.html.erb
<%= form_for(@medico) do |f| %>
  <% if @medico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medico.errors.count, "error") %> prohibited this medico from being saved:</h2>

      <ul>
      <% @medico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :crm %><br>
    <%= f.text_field :crm %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

admin/app/views/medicos/edit.html.erb
<h1>Editing Medico</h1>

<%= render 'form' %>

<%= link_to 'Show', @medico %> |
<%= link_to 'Back', medicos_path %>

admin/app/views/medicos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Medicos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Crm</th>
      <th>Telefone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medicos.each do |medico| %>
      <tr>
        <td><%= medico.nome %></td>
        <td><%= medico.crm %></td>
        <td><%= medico.telefone %></td>
        <td><%= link_to 'Show', medico %></td>
        <td><%= link_to 'Edit', edit_medico_path(medico) %></td>
        <td><%= link_to 'Destroy', medico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medico', new_medico_path %>

admin/app/views/medicos/new.html.erb
<h1>New Medico</h1>

<%= render 'form' %>

<%= link_to 'Back', medicos_path %>

admin/app/views/medicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @medico.nome %>
</p>

<p>
  <strong>Crm:</strong>
  <%= @medico.crm %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @medico.telefone %>
</p>

<%= link_to 'Edit', edit_medico_path(@medico) %> |
<%= link_to 'Back', medicos_path %>