admin/config/routes.rb
Rails.application.routes.draw do
  resources :pacientes
  resources :usuarios

  root 'home#index'
  get 'login' => 'login#login'
  get 'logout' => 'login#logout'
  post 'logar' => 'login#logar'

  get 'medicos' => 'medicos#index'
  get 'medico/cadastrar' => 'medicos#new', as: :new_medico
  get 'medico/:id' =>'medicos#show', as: :medico
  get 'medico/:id/editar' => 'medicos#edit', as: :edit_medico
  patch 'medico/:id' => 'medicos#update'
  delete 'medico/:id' => 'medicos#destroy'
  post 'medicos' => 'medicos#create'

  get 'sobre' => 'about#index'

  get 'tipos' => 'tipos#index'
  get 'tipos/:id/editar' => 'tipos#edit', as: :editar_tipo
  post 'tipos/:id/update' => 'tipos#update', as: :tipo_update
  get 'tipos/:id' => 'tipos#show', as: :tipo
  delete 'tipos/:id/delete' => 'tipos#delete', as: :tipo_delete
  get 'tipo/novo' => 'tipos#new', as: :tipo_new
  post 'tipo/criar' => 'tipos#criar', as: :tipo_criar

  get 'visitas' => 'visitas#index', as: :visita_index
  get 'visitas/novo' => 'visitas#new', as: :visita_new
  post 'visitas/criar' => 'visitas#criar', as: :visita_criar
  get 'visitas/:id' => 'visitas#show', as: :visita
  get 'visitas/:id/editar' => 'visitas#edit', as: :edit_visita
  post 'visitas/:id' => 'visitas#update', as: :visita_update
  delete 'visitas/:id/delete' => 'visitas#delete', as: :visita_delete

  get 'assistentes' => 'assistentes#index', as: :assistente_index
  get 'assistentes/novo' => 'assistentes#new', as: :assistente_new
  post 'assistentes/criar' => 'assistentes#criar', as: :assistente_criar
  get 'assistentes/:id' => 'assistentes#show', as: :assistente
  get 'assistentes/:id/edit' => 'assistentes#edit', as: :edit_assistente
  post 'assistentes/:id' => 'assistentes#update', as: :assistente_update
  delete 'assistentes/:id/delete' => 'assistentes#delete', as: :assistente_delete

end

admin/app/models/tipo.rb
class Tipo < ActiveRecord::Base
end

admin/app/controllers/tipos_controller.rb
class TiposController < ApplicationController

	def index
		@tipos=Tipo.all
	end

	def edit
		@tipo=Tipo.find_by_id(params[:id])
		render :editar
	end

	def show
		@tipo=Tipo.find_by_id(params[:id])
	end

	def update
		tipo = Tipo.find_by_id(params[:id])
    tipo.tipo = params[:tipo]
    tipo.descricao = params[:descricao]
    tipo.save
    redirect_to tipos_path
  end

  def delete
		tipo=Tipo.find_by_id(params[:id])
		tipo.destroy if tipo.present?
    redirect_to tipos_path
  end

  def new
  end

  def criar
		tipo=Tipo.new
		tipo.tipo = params[:tipo]
		tipo.descricao = params[:descricao]
		tipo.save
    redirect_to tipos_path
  end
end

admin/app/helpers/tipos_helper.rb
module TiposHelper
	def link_para_home
		raw "<a href='#{tipos_path}'>Home</a>"
	end
end

admin/app/views/tipos/_form.html.erb
<form action="<%=url%>" method="POST">
	<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	Tipo: <input type="text" name="tipo" value="<%= tipo.tipo%>"><br>
	Descrição: <textarea name="descricao"><%= tipo.descricao%></textarea><br>
	<input type="submit" value="Ok">
</form>

admin/app/views/tipos/editar.html.erb
<%= render "form", {url: tipo_update_path(@tipo), tipo: @tipo}

admin/app/views/tipos/index.html.erb
<h1> Tipos </h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Descrição</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipos.each do |tipo| %>
      <tr>
        <td><%= tipo.tipo %></td>
        <td><%= tipo.descricao %></td>
        <td><%= link_to 'Show', tipo %></td>
        <td><%= link_to 'Edit', editar_tipo_path(tipo) %></td>
        <td><%= link_to 'Destroy', tipo_delete_path(tipo), method: :delete, data: { confirm: 'Confirma exclusão?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Descrever Tipo", tipo_new_path %>

admin/app/views/tipos/new.html.erb
<%= render "form", {url: tipo_criar_path, tipo: Tipo.new} %>

admin/app/views/tipos/show.html.erb
<div>
<label>Tipo: <%= @tipo.tipo %></label>
</div>
<div>
<label>Descrição: <%= @tipo.descricao %></label>
</div>
<%= link_para_home %>