admin/config/routes.rb
Rails.application.routes.draw do
  resources :pacientes
  resources :usuarios

  root 'home#index'
  get 'login' => 'login#login'
  get 'logout' => 'login#logout'
  post 'logar' => 'login#logar'

  get 'medicos' => 'medicos#index'
  get 'medico/cadastrar' => 'medicos#new', as: :new_medico
  get 'medico/:id' =>'medicos#show', as: :medico
  get 'medico/:id/editar' => 'medicos#edit', as: :edit_medico
  patch 'medico/:id' => 'medicos#update'
  delete 'medico/:id' => 'medicos#destroy'
  post 'medicos' => 'medicos#create'

  get 'sobre' => 'about#index'

  get 'tipos' => 'tipos#index'
  get 'tipos/:id/editar' => 'tipos#edit', as: :editar_tipo
  post 'tipos/:id/update' => 'tipos#update', as: :tipo_update
  get 'tipos/:id' => 'tipos#show', as: :tipo
  delete 'tipos/:id/delete' => 'tipos#delete', as: :tipo_delete
  get 'tipo/novo' => 'tipos#new', as: :tipo_new
  post 'tipo/criar' => 'tipos#criar', as: :tipo_criar

  get 'visitas' => 'visitas#index', as: :visita_index
  get 'visitas/novo' => 'visitas#new', as: :visita_new
  post 'visitas/criar' => 'visitas#criar', as: :visita_criar
  get 'visitas/:id' => 'visitas#show', as: :visita
  get 'visitas/:id/editar' => 'visitas#edit', as: :edit_visita
  post 'visitas/:id' => 'visitas#update', as: :visita_update
  delete 'visitas/:id/delete' => 'visitas#delete', as: :visita_delete

  get 'assistentes' => 'assistentes#index', as: :assistente_index
  get 'assistentes/novo' => 'assistentes#new', as: :assistente_new
  post 'assistentes/criar' => 'assistentes#criar', as: :assistente_criar
  get 'assistentes/:id' => 'assistentes#show', as: :assistente
  get 'assistentes/:id/edit' => 'assistentes#edit', as: :edit_assistente
  post 'assistentes/:id' => 'assistentes#update', as: :assistente_update
  delete 'assistentes/:id/delete' => 'assistentes#delete', as: :assistente_delete

end

admin/app/models/visita.rb
class Visita < ActiveRecord::Base
	belongs_to :paciente
end

admin/app/controllers/visitas_controller.rb
class VisitasController < ApplicationController
  def index
    @visitas=Visita.all
  end

  def new
  end

  def criar
    visita=Visita.new
    visita.paciente.nome = params[:nome]
    visita.endereco = params[:endereco]
    visita.dia = params[:dia]
    visita.hora = params[:hora]
    visita.descricao = params[:descricao]
    visita.save
    redirect_to visita_index_path
  end
  
  def edit
    @visita=Visita.find_by_id(params[:id])
    render :editar
  end

  def update
    visita=Visita.find_by_id(params[:id])
    visita.paciente_id = params[:paciente_id]
    visita.endereco = params[:endereco]
    visita.dia = params[:dia]
    visita.hora = params[:hora]
    visita.descricao = params[:descricao]
    visita.save
    redirect_to visita_index_path
  end

  def delete
    visita=Visita.find_by_id(params[:id])
    visita.destroy if visita.present?
    redirect_to visita_index_path
  end

  def show
    @visita=Visita.find_by_id(params[:id])
  end

end

admin/app/views/visitas/_form.html.erb
<form action="<%= url %>" method="POST">
	<%= hidden_field_tag :authenticity_token, form_authenticity_token %>

	Nome:
	<select name="paciente_id" required title="Favor selecionar um paciente">
		<option value="">selecione</option>
		<% pacientes.each do |paciente| %>
	  	<option value="<%= paciente.id %>" <%= "selected" if(paciente.id == visita.paciente.id) rescue "" %>><%= paciente.nome %></option>
	  <% end %>
	</select>
	<br>

	Endereço: <input type="text" name="endereco" value="<%= visita.endereco%>" required title="digite o endereço"><br>
	Dia: <input type="date" name="dia" value="<%= visita.dia%>" required title="coloque o dia"><br>
	Horas: <input type="number" name="hora" value="<%= visita.hora%>" required title="coloque a hora"><br>
	Descrição: <textarea name="descricao"><%= visita.descricao%></textarea><br>
	<input type="submit" value="Ok">

</form>

admin/app/views/visitas/editar.html.erb
<%= render 'form', {url: visita_update_path(@visita),visita:@visita, pacientes: Paciente.all} %>

admin/app/views/visitas/index.html.erb
<h1> Visitas </h1>

<table>
  <thead>
    <tr>
      <th>Nome do Paciente</th>
      <th>Endereço</th>
      <th>Dia</th>
      <th>Horas</th>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visitas.each do |visita| %>
      <tr>
        <td><%= visita.paciente.nome %></td>
        <td><%= visita.endereco %></td>
        <td><%= visita.dia %></td>
        <td><%= visita.hora %></td>
        <td><%= visita.descricao %></td>
        <td><%= link_to 'Show', visita_path(visita) %></td>
        <td><%= link_to 'Edit', edit_visita_path(visita) %></td>
        <td><%= link_to 'Destroy', visita_delete_path(visita), method: :delete, data: { confirm: 'Confirma exclusão?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Cadastrar visita", visita_new_path %>

admin/app/views/visitas/new.html.erb
<%= render 'form', {url: visita_criar_path, visita:Visita.new, pacientes: Paciente.all} %>

admin/app/views/visitas/show.html.erb
<div>
<label>Nome: <%= @visita.paciente.nome %></label>
</div>
<div>
<label>Endereço: <%= @visita.endereco %></label>
</div>
<div>
<label>Dia: <%= @visita.dia %></label>
</div>
<div>
<label>Hora: <%= @visita.hora %></label>
</div>
<div>
<label>Descrição: <%= @visita.descricao %></label>
</div>
<%= link_to 'Visitas', visita_index_path %>