admin/config/routes.rb
Rails.application.routes.draw do
  resources :pacientes
  resources :usuarios

  root 'home#index'
  get 'login' => 'login#login'
  get 'logout' => 'login#logout'
  post 'logar' => 'login#logar'

  get 'medicos' => 'medicos#index'
  get 'medico/cadastrar' => 'medicos#new', as: :new_medico
  get 'medico/:id' =>'medicos#show', as: :medico
  get 'medico/:id/editar' => 'medicos#edit', as: :edit_medico
  patch 'medico/:id' => 'medicos#update'
  delete 'medico/:id' => 'medicos#destroy'
  post 'medicos' => 'medicos#create'

  get 'sobre' => 'about#index'

  get 'tipos' => 'tipos#index'
  get 'tipos/:id/editar' => 'tipos#edit', as: :editar_tipo
  post 'tipos/:id/update' => 'tipos#update', as: :tipo_update
  get 'tipos/:id' => 'tipos#show', as: :tipo
  delete 'tipos/:id/delete' => 'tipos#delete', as: :tipo_delete
  get 'tipo/novo' => 'tipos#new', as: :tipo_new
  post 'tipo/criar' => 'tipos#criar', as: :tipo_criar

  get 'visitas' => 'visitas#index', as: :visita_index
  get 'visitas/novo' => 'visitas#new', as: :visita_new
  post 'visitas/criar' => 'visitas#criar', as: :visita_criar
  get 'visitas/:id' => 'visitas#show', as: :visita
  get 'visitas/:id/editar' => 'visitas#edit', as: :edit_visita
  post 'visitas/:id' => 'visitas#update', as: :visita_update
  delete 'visitas/:id/delete' => 'visitas#delete', as: :visita_delete

  get 'assistentes' => 'assistentes#index', as: :assistente_index
  get 'assistentes/novo' => 'assistentes#new', as: :assistente_new
  post 'assistentes/criar' => 'assistentes#criar', as: :assistente_criar
  get 'assistentes/:id' => 'assistentes#show', as: :assistente
  get 'assistentes/:id/edit' => 'assistentes#edit', as: :edit_assistente
  post 'assistentes/:id' => 'assistentes#update', as: :assistente_update
  delete 'assistentes/:id/delete' => 'assistentes#delete', as: :assistente_delete

end

admin/app/models/assistente.rb
class Assistente < ActiveRecord::Base
end

admin/app/controllers/assistentes_controller.rb
class AssistentesController < ApplicationController
  def index
    @assistentes=Assistente.all
  end

  def new
  end


def criar
    assistente=Assistente.new
    assistente.nome = params[:nome]
    assistente.chapa = params[:chapa]
    assistente.cargo = params[:cargo]
    assistente.save
    redirect_to assistente_index_path
  end

  def show
    @assistente=Assistente.find_by_id(params[:id])
  end

  def edit
    @assistente=Assistente.find_by_id(params[:id])
    render :edit
  end

  def update
    assistente=Assistente.find_by_id(params[:id])
    assistente.nome = params[:nome]
    assistente.chapa = params[:chapa]
    assistente.cargo = params[:cargo]
    assistente.save
    redirect_to assistente_index_path
  end

  def delete
    assistente=Assistente.find_by_id(params[:id])
    assistente.destroy if assistente.present?
    redirect_to assistente_index_path
  end

end  

admin/app/views/assistentes/_form.html.erb
<form action="<%=url%>" method="POST">
	<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	Nome: <input type="text" name="nome" value="<%= assistente.nome%>" required title="digite o nome"><br>
	Número da Chapa: <input type="text" name="chapa" value="<%= assistente.chapa%>"required title="digite a chapa"><br>
	Cargo: <input type="text" name="cargo" value="<%= assistente.cargo%>"required title="digite o cargo"><br>
	<input type="submit" value="Ok">
</form>

admin/app/views/assistentes/edit.html.erb
<%= render 'form', {url: assistente_update_path(@assistente),assistente:@assistente} %>

admin/app/views/assistentes/index.html.erb
<h1> Assistentes </h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Número da chapa</th>
      <th>Cargo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assistentes.each do |assistente| %>
      <tr>
        <td><%= assistente.nome %></td>
        <td><%= assistente.chapa %></td>
        <td><%= assistente.cargo %></td>
        <td><%= link_to 'Show', assistente_path(assistente) %></td>
        <td><%= link_to 'Edit', edit_assistente_path(assistente) %></td>
        <td><%= link_to 'Destroy', assistente_delete_path(assistente), method: :delete, data: { confirm: 'Confirma exclusão dessa-porra?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Cadastrar assistente", assistente_new_path %>

admin/app/views/assistentes/new.html.erb
<%= render "form", {url: assistente_criar_path, assistente: Assistente.new} %>

admin/app/views/assistentes/show.html.erb
<div>
<label>Nome: <%= @assistente.nome %></label>
</div>
<div>
<label>Número da Chapa: <%= @assistente.chapa %></label>
</div>
<div>
<label>Cargo: <%= @assistente.cargo %></label>
</div>
<%= link_to 'Assistentes', assistente_index_path %>